/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FloorPrice: typeof import('./src/components/charts/Floor-Price.vue')['default']
    GuangZhouMap: typeof import('./src/components/charts/GuangZhouMap.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RoomAmountPrice: typeof import('./src/components/charts/RoomAmount-Price.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
