/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AreaPrice: typeof import('./components/charts/Area-Price.vue')['default']
    AvgPrice: typeof import('./components/charts/AvgPrice.vue')['default']
    BoxPrice: typeof import('./components/charts/BoxPrice.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElText: typeof import('element-plus/es')['ElText']
    FloorPrice: typeof import('./components/charts/Floor-Price.vue')['default']
    GuangZhouMap: typeof import('./components/charts/GuangZhouMap.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    PredictionBySpace: typeof import('./components/predictions/PredictionBySpace.vue')['default']
    RoomAmountPrice: typeof import('./components/charts/RoomAmount-Price.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpacePrice: typeof import('./components/charts/Space-Price.vue')['default']
  }
}
